#ifndef SIGNALMGR_H
#define SIGNALMGR_H

#include <libopencm3/stm32/gpio.h>

/* Created March 21, 2026
This file is going to be home for our signal generation functions
*/

// signal generated by toggling a GPIO pin at maximum speed, by setting 
//and resetting the BSRR register for the pin. 
void SignOfLifeSignalAtMaximumSpeed(uint32_t gpioPort, uint32_t gpioPin);


#endif