
//1. Sign of life test 
// // signal generated by toggling a GPIO pin at maximum speed, by setting 
// //and resetting the BSRR register for the pin. 

// #define SIGNOFLIFEPORT GPIOA
// #define SIGNOFLIFEPIN GPIO9   // PA9
// signal generated by toggling a GPIO pin at maximum speed, by setting 
// //and resetting the BSRR register for the pin. 
// void SignOfLifeSignalAtMaximumSpeed(uint32_t gpioPort, uint32_t gpioPin);

// void SignOfLifeSignalAtMaximumSpeed(uint32_t gpioPort, uint32_t gpioPin) {
//         GPIO_BSRR(gpioPort) = gpioPin;  
//         GPIO_BSRR(gpioPort)  = gpioPin << 16; // reset the pin by writing to the upper half of the BSRR register
// }

// // usage:Sign of life test
//     // rcc_clock_setup_in_hse_8mhz_out_48mhz();
//     // rcc_periph_clock_enable(RCC_GPIOA);
        // gpio_mode_setup(gpioPort, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, gpioPin); use this first 
//      // SignOfLifeSignalAtMaximumSpeed(SIGNOFLIFEPORT, SIGNOFLIFEPIN);


