#include "SignalMgr.h"
#include <libopencm3/stm32/gpio.h>

// signal generated by toggling a GPIO pin at maximum speed, by setting 
//and resetting the BSRR register for the pin. 
void SignOfLifeSignalAtMaximumSpeed(uint32_t gpioPort, uint32_t gpioPin) {
        GPIO_BSRR(gpioPort) = gpioPin;  
        GPIO_BSRR(gpioPort)  = gpioPin << 16; // reset the pin by writing to the upper half of the BSRR register
}