// #include <libopencm3/stm32/gpio.h>

// // signal generated by toggling a GPIO pin at maximum speed, by setting 
// //and resetting the BSRR register for the pin. 
// // usage:Sign of life test
//     // rcc_clock_setup_in_hse_8mhz_out_48mhz();
//     // rcc_periph_clock_enable(RCC_GPIOA);
//     // SignOfLifeSignalAtMaximumSpeed(SIGNOFLIFEPORT, SIGNOFLIFEPIN);
    
    
//         // gpio_mode_setup(gpioPort, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, gpioPin); use this first 
// void SignOfLifeSignalAtMaximumSpeed(uint32_t gpioPort, uint32_t gpioPin) {
//         GPIO_BSRR(gpioPort) = gpioPin;  
//         GPIO_BSRR(gpioPort)  = gpioPin << 16; // reset the pin by writing to the upper half of the BSRR register
// }